namespace Logging.complex;

  public enum VKeys
    {
        Back = 0x08,        
        Tab = 0x09,         
        Return = 0x0D,
        Pause = 0x13,
        CapsLock = 0x14,

        Escape = 0x1B,
        Space = 0x20,
        End = 0x23,
        Home = 0x24,
        Left = 0x25,
        Up = 0x26,          
        Right = 0x27,       
        Down = 0x28,        
        Print = 0x2A,       
        Insert = 0x2D,      
        Delete = 0x2E,      
        
        Key0 = 0x30,       
        Key1 = 0x31,       
        Key2 = 0x32,       
        Key3 = 0x33,       
        Key4 = 0x34,       
        Key5 = 0x35,       
        Key6 = 0x36,       
        Key7 = 0x37,       
        Key8 = 0x38,       
        Key9 = 0x39,       

        KeyA = 0x41,       
        KeyB = 0x42,       
        KeyC = 0x43,       
        KeyD = 0x44,       
        KeyE = 0x45,       
        KeyF = 0x46,       
        KeyG = 0x47,       
        KeyH = 0x48,       
        KeyI = 0x49,       
        KeyJ = 0x4A,       
        KeyK = 0x4B,       
        KeyL = 0x4C,       
        KeyM = 0x4D,       
        KeyN = 0x4E,       
        KeyO = 0x4F,       
        KeyP = 0x50,       
        KeyQ = 0x51,       
        KeyR = 0x52,       
        KeyS = 0x53,       
        KeyT = 0x54,       
        KeyU = 0x55,       
        KeyV = 0x56,       
        KeyW = 0x57,       
        KeyX = 0x58,       
        KeyY = 0x59,       
        KeyZ = 0x5A,       
        
        Lwin = 0x5B,        
        Rwin = 0x5C,        
        Apps = 0x5D,        
        
        Numpad0 = 0x60,     
        Numpad1 = 0x61,     
        Numpad2 = 0x62,     
        Numpad3 = 0x63,     
        Numpad4 = 0x64,     
        Numpad5 = 0x65,     
        Numpad6 = 0x66,     
        Numpad7 = 0x67,     
        Numpad8 = 0x68,     
        Numpad9 = 0x69,     
        
        Multiply = 0x6A,    
        Add = 0x6B,         
        Subtract = 0x6D,    
        Separator = 0x6E,   
        Divide = 0x6F,      
        
        F1 = 0x70,          
        F2 = 0x71,          
        F3 = 0x72,          
        F4 = 0x73,          
        F5 = 0x74,          
        F6 = 0x75,          
        F7 = 0x76,          
        F8 = 0x77,          
        F9 = 0x78,          
        F10 = 0x79,         
        F11 = 0x7A,         
        F12 = 0x7B,         
      
        
        Lshift = 0xA0,      
        Rshift = 0xA1,      
        Lcontrol = 0xA2,    
        Rcontrol = 0xA3,    
        Lwindows = 0xA4,       
        Rwindows = 0xA5,       
                            
        OemPlus = 0xBB,    
        OemComma = 0xBC,   
        OemMinus = 0xBD,   
        OemPeriod = 0xBE,  
        Hashtag = 0xBF,     
                            
        NextKey0 = 0xDB,  
        NextKey1 = 0xDC,  
        NextBack = 0xDD,   
                            
        SpecialA = 0xDE,   
        SpecialO = 0xC0,   
        SpecialU = 0xBA,   
        
        KeySmaller = 0xE2, 
    }